version: "3.9"

networks: 
    sqlserverNET:
    demodockerNET: 

services:

    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        container_name: sqlservercontainer
        ports: 
            - "1433:1433"
        networks: 
            - sqlserverNET
        environment: 
            ACCEPT_EULA: "Y" 
            SA_PASSWORD: "MY_password123"

    demodocker:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: demodockercontainer
        networks: 
            - sqlserverNET
            - demodockerNET
        ports:
            - 5000:80
        environment: 
            - DBHOST=sqlserver
        depends_on: 
            - sqlserver